# Cloud Build configuration for ClipScribe v2.44.0
# Optimized Docker build and Cloud Run deployment with multi-stage builds

steps:
  # Build and push CLI image (smallest)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=cli'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-cli:v2.44.0'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-cli:latest'
      - '.'
    timeout: 600s
    env:
      - 'DOCKER_BUILDKIT=1'

  # Build and push API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=api'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-api:v2.44.0'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-api:latest'
      - '.'
    timeout: 800s
    env:
      - 'DOCKER_BUILDKIT=1'

  # Build and push Web image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=web'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-web:v2.44.0'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-web:latest'
      - '.'
    timeout: 900s
    env:
      - 'DOCKER_BUILDKIT=1'

  # Build and push Worker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=worker'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-worker:v2.44.0'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-worker:latest'
      - '.'
    timeout: 1000s
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push all images in parallel
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-cli:v2.44.0'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-api:v2.44.0'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-web:v2.44.0'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-worker:v2.44.0'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-cli:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-api:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-web:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-worker:latest'

  # CLI service deployment skipped - CLI is for local command-line usage

  # Deploy API service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'clipscribe-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clipscribe-api:v2.44.0'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1,CLIPSCRIBE_LOG_LEVEL=INFO,WORKER_TIMEOUT=3600,MAX_WORKERS=4,GOOGLE_API_KEY=AIzaSyATh0jBERyWBl5_wL-2Y6COte2FF0aFGnw,CORS_ALLOW_ORIGINS=https://clipscribe.ai'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest,GCS_BUCKET=GCS_BUCKET:latest'
      - '--port'
      - '8000'
      - '--execution-environment=gen2'
      - '--no-cpu-boost'
      - '--cpu=1'
      - '--memory=2Gi'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--concurrency=50'
      - '--timeout=300s'
      - '--vpc-connector=clipscribe-connector'
      - '--vpc-egress=all-traffic'

  # Deploy Web service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'clipscribe-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clipscribe-web:v2.44.0'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1.5Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '1800'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'CLIPSCRIBE_API_URL=https://clipscribe-api-$PROJECT_NUMBER.us-central1.run.app,PYTHONUNBUFFERED=1,CLIPSCRIBE_LOG_LEVEL=INFO'

  # Deploy Worker service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'clipscribe-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clipscribe-worker:v2.44.0'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'  # Worker should not be publicly accessible
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1,CLIPSCRIBE_LOG_LEVEL=INFO,WORKER_MODE=cloud-run'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest,GCS_BUCKET=GCS_BUCKET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--vpc-connector=clipscribe-connector'
      - '--vpc-egress=all-traffic'
      - '--execution-environment=gen2'
      - '--no-cpu-boost'

# Build timeout (15 minutes for all builds)
timeout: 1800s

# Options for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  env:
    - 'DOCKER_BUILDKIT=1'

# Use Container Registry for storing images
images:
  - 'gcr.io/$PROJECT_ID/clipscribe-cli:v2.43.0'
  - 'gcr.io/$PROJECT_ID/clipscribe-api:v2.43.0'
  - 'gcr.io/$PROJECT_ID/clipscribe-web:v2.43.0'
  - 'gcr.io/$PROJECT_ID/clipscribe-worker:v2.43.0'
