# Cloud Build configuration for Cloud Run Jobs deployment
# This deploys the worker as a Cloud Run Job instead of a Service

steps:
  # Create service account if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-service-account'
    entrypoint: 'gcloud'
    args:
      - 'iam'
      - 'service-accounts'
      - 'create'
      - 'clipscribe-worker'
      - '--display-name=ClipScribe Worker Service Account'
      - '--description=Service account for ClipScribe Cloud Run Jobs'
      - '--project=${PROJECT_ID}'

  # Setup IAM permissions for service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-iam'
    waitFor: ['create-service-account']
    entrypoint: 'gcloud'
    args:
      - 'iam'
      - 'service-accounts'
      - 'add-iam-policy-binding'
      - 'clipscribe-worker@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--member=serviceAccount:clipscribe-worker@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--role=roles/iam.serviceAccountUser'

  # Build the job worker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-job-worker'
    waitFor: ['setup-iam']
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipscribe-job-worker:latest'
      - '-f'
      - 'Dockerfile.job'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-job-worker'
    waitFor: ['build-job-worker']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-job-worker-latest'
    waitFor: ['build-job-worker']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipscribe-job-worker:latest'

  # Deploy Flash Model Job (for high-volume, cost-sensitive processing)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-flash-job'
    waitFor: ['push-job-worker']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'clipscribe-worker-flash'
      - '--image=gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'
      - '--region=${_REGION}'
      - '--parallelism=1'

      - '--max-retries=2'
      - '--task-timeout=86400'  # 24 hours
      - '--memory=4Gi'
      - '--cpu=2'
      - '--set-env-vars=USE_PRO_MODEL=false,CLIPSCRIBE_LOG_LEVEL=INFO,VIDEO_CACHE_DIR=/cache'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest,GCS_BUCKET=GCS_BUCKET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--service-account=clipscribe-worker@$PROJECT_ID.iam.gserviceaccount.com'
      - '--vpc-connector=projects/$PROJECT_ID/locations/${_REGION}/connectors/clipscribe-connector'
      - '--vpc-egress=all-traffic'


  # Update Flash Job if it already exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-flash-job'
    waitFor: ['deploy-flash-job']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'clipscribe-worker-flash'
      - '--image=gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'
      - '--region=${_REGION}'
      - '--parallelism=1'

      - '--max-retries=2'
      - '--task-timeout=86400'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--set-env-vars=USE_PRO_MODEL=false,CLIPSCRIBE_LOG_LEVEL=INFO,VIDEO_CACHE_DIR=/cache'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest,GCS_BUCKET=GCS_BUCKET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'

  # Deploy Pro Model Job (for high-quality, premium processing)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-pro-job'
    waitFor: ['push-job-worker']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'clipscribe-worker-pro'
      - '--image=gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'
      - '--region=${_REGION}'
      - '--parallelism=1'

      - '--max-retries=2'
      - '--task-timeout=86400'
      - '--memory=8Gi'
      - '--cpu=4'
      - '--set-env-vars=USE_PRO_MODEL=true,CLIPSCRIBE_LOG_LEVEL=INFO,VIDEO_CACHE_DIR=/cache'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest,GCS_BUCKET=GCS_BUCKET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--service-account=clipscribe-worker@$PROJECT_ID.iam.gserviceaccount.com'
      - '--vpc-connector=projects/$PROJECT_ID/locations/${_REGION}/connectors/clipscribe-connector'
      - '--vpc-egress=all-traffic'


  # Update Pro Job if it already exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-pro-job'
    waitFor: ['deploy-pro-job']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'clipscribe-worker-pro'
      - '--image=gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'
      - '--region=${_REGION}'
      - '--parallelism=1'

      - '--max-retries=2'
      - '--task-timeout=86400'
      - '--memory=8Gi'
      - '--cpu=4'
      - '--set-env-vars=USE_PRO_MODEL=true,CLIPSCRIBE_LOG_LEVEL=INFO,VIDEO_CACHE_DIR=/cache'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest,GCS_BUCKET=GCS_BUCKET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'

  # Create Cloud Scheduler jobs to trigger workers periodically
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-scheduler-flash'
    waitFor: ['update-flash-job']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create scheduler for Flash worker (runs every 5 minutes)
        gcloud scheduler jobs create http clipscribe-flash-scheduler \
          --location=${_REGION} \
          --schedule="*/5 * * * *" \
          --uri="https://run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/clipscribe-worker-flash:run" \
          --http-method=POST \
          --oauth-service-account-email=clipscribe-scheduler@$PROJECT_ID.iam.gserviceaccount.com \
          || gcloud scheduler jobs update http clipscribe-flash-scheduler \
            --location=${_REGION} \
            --schedule="*/5 * * * *" \
            --uri="https://run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/clipscribe-worker-flash:run"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-scheduler-pro'
    waitFor: ['update-pro-job']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create scheduler for Pro worker (runs every 10 minutes)
        gcloud scheduler jobs create http clipscribe-pro-scheduler \
          --location=${_REGION} \
          --schedule="*/10 * * * *" \
          --uri="https://run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/clipscribe-worker-pro:run" \
          --http-method=POST \
          --oauth-service-account-email=clipscribe-scheduler@$PROJECT_ID.iam.gserviceaccount.com \
          || gcloud scheduler jobs update http clipscribe-pro-scheduler \
            --location=${_REGION} \
            --schedule="*/10 * * * *" \
            --uri="https://run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/clipscribe-worker-pro:run"

# Substitutions
substitutions:
  _VERSION: 'v2.46.0'
  _REGION: 'us-central1'

# Build configuration
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  env:
    - 'DOCKER_BUILDKIT=1'

# Store images
images:
  - 'gcr.io/$PROJECT_ID/clipscribe-job-worker:${_VERSION}'
  - 'gcr.io/$PROJECT_ID/clipscribe-job-worker:latest'
