"""
Upload X drafts to Google Cloud Storage for mobile access.

Creates mobile-optimized HTML pages for reviewing drafts.
Handles 72-hour auto-deletion of videos.
"""

import logging
from pathlib import Path
from typing import Dict, Optional
from google.cloud import storage
from datetime import timedelta

logger = logging.getLogger(__name__)


def generate_draft_page(
    tweet_text: str,
    video_title: str,
    entity_count: int,
    relationship_count: int,
    thumbnail_filename: str = "thumbnail.jpg",
    video_filename: str = "video.mp4"
) -> str:
    """
    Generate mobile-optimized HTML page for draft review.
    
    Optimized for Pixel 9 Pro:
    - One-tap copy
    - Easy media download
    - Clean, fast interface
    """
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>X Draft - {video_title[:50]}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #000;
            color: #fff;
        }}
        .container {{
            max-width: 600px;
            margin: 0 auto;
        }}
        h1 {{
            font-size: 20px;
            margin-bottom: 10px;
        }}
        .stats {{
            color: #71767b;
            font-size: 14px;
            margin-bottom: 20px;
        }}
        .tweet-box {{
            background: #16181c;
            border: 1px solid #2f3336;
            border-radius: 16px;
            padding: 16px;
            margin-bottom: 20px;
        }}
        #tweet-text {{
            font-size: 16px;
            line-height: 1.5;
            margin-bottom: 12px;
            white-space: pre-wrap;
        }}
        .char-count {{
            color: #71767b;
            font-size: 14px;
            margin-bottom: 12px;
        }}
        button {{
            background: #1d9bf0;
            color: #fff;
            border: none;
            border-radius: 24px;
            padding: 12px 24px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            width: 100%;
            margin-bottom: 12px;
        }}
        button:active {{
            background: #1a8cd8;
        }}
        .media-section {{
            margin-top: 20px;
        }}
        .media-item {{
            background: #16181c;
            border: 1px solid #2f3336;
            border-radius: 16px;
            padding: 16px;
            margin-bottom: 16px;
        }}
        img, video {{
            max-width: 100%;
            border-radius: 12px;
            display: block;
            margin: 12px 0;
        }}
        .success {{
            background: #00ba7c;
            color: #fff;
            padding: 12px;
            border-radius: 8px;
            margin-top: 12px;
            display: none;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{video_title}</h1>
        <div class="stats">
            📊 {entity_count} entities • {relationship_count} relationships
        </div>
        
        <div class="tweet-box">
            <div id="tweet-text">{tweet_text}</div>
            <div class="char-count">{len(tweet_text)} / 280 characters</div>
            <button onclick="copyText()">📋 Copy Tweet Text</button>
            <div id="copy-success" class="success">✅ Copied to clipboard!</div>
        </div>
        
        <div class="media-section">
            <div class="media-item">
                <h3>🖼️ Thumbnail</h3>
                <img src="{thumbnail_filename}" alt="Thumbnail">
                <button onclick="window.open('{thumbnail_filename}', '_blank')">⬇️ Download Thumbnail</button>
            </div>
            
            <div class="media-item">
                <h3>🎥 Video</h3>
                <video src="{video_filename}" controls></video>
                <button onclick="window.open('{video_filename}', '_blank')">⬇️ Download Video</button>
            </div>
        </div>
        
        <div style="margin-top: 40px; text-align: center; color: #71767b; font-size: 14px;">
            Generated by ClipScribe v2.53.0
        </div>
    </div>
    
    <script>
        function copyText() {{
            const text = document.getElementById('tweet-text').innerText;
            navigator.clipboard.writeText(text).then(() => {{
                const success = document.getElementById('copy-success');
                success.style.display = 'block';
                setTimeout(() => success.style.display = 'none', 2000);
            }});
        }}
    </script>
</body>
</html>"""
    
    return html


class GCSUploader:
    """
    Upload X drafts to Google Cloud Storage.
    
    Features:
    - Mobile-optimized HTML pages
    - Public URLs for Telegram links
    - 72-hour auto-deletion
    - Thumbnail + video hosting
    """
    
    def __init__(self, bucket_name: str = "clipscribe-drafts"):
        """
        Initialize GCS uploader.
        
        Args:
            bucket_name: GCS bucket name
        """
        self.bucket_name = bucket_name
        
        try:
            # Use Application Default Credentials (ADC)
            self.client = storage.Client(project="prismatic-iris-429006-g6")
            self.bucket = self.client.bucket(bucket_name)
            
            # Set 72-hour lifecycle rule
            self.bucket.add_lifecycle_delete_rule(age=3)  # 3 days
            self.bucket.patch()
            
            logger.info(f"GCSUploader initialized: {bucket_name}")
        except Exception as e:
            logger.error(f"GCS initialization failed: {e}")
            self.bucket = None
    
    async def upload_draft(
        self,
        draft_id: str,
        tweet_text: str,
        video_title: str,
        entity_count: int,
        relationship_count: int,
        thumbnail_path: Optional[Path],
        video_path: Optional[Path]
    ) -> Optional[str]:
        """
        Upload complete draft to GCS.
        
        Returns:
            URL to draft review page
        """
        if not self.bucket:
            logger.warning("GCS not configured, skipping upload")
            return None
        
        try:
            # Generate HTML page
            html = generate_draft_page(
                tweet_text=tweet_text,
                video_title=video_title,
                entity_count=entity_count,
                relationship_count=relationship_count
            )
            
            # Upload HTML
            blob_html = self.bucket.blob(f"drafts/{draft_id}/index.html")
            blob_html.upload_from_string(html, content_type="text/html")
            # Public via bucket IAM policy (uniform access)
            
            # Upload thumbnail if exists
            if thumbnail_path and thumbnail_path.exists():
                blob_thumb = self.bucket.blob(f"drafts/{draft_id}/thumbnail.jpg")
                blob_thumb.upload_from_filename(str(thumbnail_path))
            
            # Upload video if exists
            if video_path and video_path.exists():
                blob_video = self.bucket.blob(f"drafts/{draft_id}/video.mp4")
                blob_video.upload_from_filename(str(video_path))
            
            # Return public URL
            draft_url = blob_html.public_url
            logger.info(f"Uploaded draft to GCS: {draft_url}")
            
            return draft_url
            
        except Exception as e:
            logger.error(f"Failed to upload draft to GCS: {e}")
            return None


async def test_uploader():
    """Test GCS upload with sample draft."""
    uploader = GCSUploader()
    
    url = await uploader.upload_draft(
        draft_id="test_123",
        tweet_text="Test tweet text here...",
        video_title="Test Video",
        entity_count=10,
        relationship_count=5,
        thumbnail_path=None,
        video_path=None
    )
    
    print(f"Draft URL: {url}")


if __name__ == "__main__":
    asyncio.run(test_uploader())

